#!/bin/bash
cd $OPENSHIFT_REPO_DIR/config/autoload
sleep 2
export OPENSHIFT_CONFIG=$OPENSHIFT_REPO_DIR/config/autoload/openshift.config.php.dist
echo "Copiando $OPENSHIFT_CONFIG"
cp -v $OPENSHIFT_CONFIG $OPENSHIFT_REPO_DIR/config/autoload/openshift.config.php
echo "Se a copiado la configuración correctamente"

cd $OPENSHIFT_REPO_DIR
curl -sS https://getcomposer.org/installer | php
./composer.phar self-update
./composer.phar install